name: Update Weather

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  update-weather:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Get Weather
      env:
        TEMPEST_PUT: ${{ secrets.TEMPEST_PUT }}
      run: python .github/update-weather.py
    - name: Configure Git
      run: git config --global user.name "Leo Herzog" && git config --global user.email "leo@herzog.tech"
    - name: Commit Changes
      run: git add README.md && git commit -m "Update Weather" && git push || echo "No changes"
